-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 17:10:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT(11) NOT NULL,
  `nom` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`magasins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`magasins` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`commandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commandes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idMagasin` INT(11) NOT NULL,
  `idClient` INT(11) NOT NULL,
  `dateCom` DATETIME NOT NULL,
  `dateLiv` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idMagasin` (`idMagasin` ASC),
  INDEX `idClient` (`idClient` ASC),
  CONSTRAINT `commandes_ibfk_1`
    FOREIGN KEY (`idMagasin`)
    REFERENCES `mydb`.`magasins` (`id`),
  CONSTRAINT `commandes_ibfk_2`
    FOREIGN KEY (`idClient`)
    REFERENCES `mydb`.`clients` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produits` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `prix` DOUBLE NULL DEFAULT NULL,
  `estPrixDuJour` TINYINT(4) NOT NULL DEFAULT '0',
  `cat` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `cat_idx` (`cat` ASC),
  CONSTRAINT `cat`
    FOREIGN KEY (`cat`)
    REFERENCES `mydb`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2043
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`produitscommandes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produitscommandes` (
  `idCommande` INT(11) NOT NULL,
  `idProduit` INT(11) NOT NULL,
  `total` INT(11) NOT NULL,
  PRIMARY KEY (`idCommande`, `idProduit`),
  INDEX `idProduit` (`idProduit` ASC),
  CONSTRAINT `produitscommandes_ibfk_1`
    FOREIGN KEY (`idCommande`)
    REFERENCES `mydb`.`commandes` (`id`),
  CONSTRAINT `produitscommandes_ibfk_2`
    FOREIGN KEY (`idProduit`)
    REFERENCES `mydb`.`produits` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
